table imdb_movies
	lineageTag: 909ede33-438d-4fa4-9089-72aa6793aafb

	measure 'Total de Filmes' = COUNTROWS('imdb_movies')
		formatString: 0
		lineageTag: 612a98a7-a89c-4ebf-a178-13a172079327

	measure 'Média IMDB Pós-2000' =
			
			CALCULATE(
			    AVERAGE('imdb_movies'[nota]),
			    'imdb_movies'[ano]>= 2000
			)
		lineageTag: b441edfa-91fa-4517-83ad-159babb72ece

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultado Financeiro Total' =
			
			SUMX(
			    'imdb_movies',
			    'imdb_movies'[gross_world_wide] - 'imdb_movies'[budget]
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: d3d0468c-2f97-4d6a-bb56-218802aa8985

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column id
		dataType: string
		lineageTag: 62eb7a2b-8ea9-408b-95eb-8bd479d2ef28
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column titulo
		dataType: string
		lineageTag: 1cca1055-ce2b-4412-8775-f623e03e0612
		summarizeBy: none
		sourceColumn: titulo

		annotation SummarizationSetBy = Automatic

	column ano
		dataType: int64
		formatString: 0
		lineageTag: eeff16f6-ff01-4c8e-835a-43eeebc73949
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column duracao
		dataType: string
		lineageTag: dbb0d648-d09b-4c0c-9abb-d67c47d7b251
		summarizeBy: none
		sourceColumn: duracao

		annotation SummarizationSetBy = Automatic

	column nota
		dataType: int64
		formatString: 0
		lineageTag: b5eea345-d8a8-4430-9a5a-e148b7a136ed
		summarizeBy: sum
		sourceColumn: nota

		annotation SummarizationSetBy = Automatic

	column votos
		dataType: int64
		formatString: 0
		lineageTag: ac26971c-6fdd-4674-a005-2c1f95476fbc
		summarizeBy: sum
		sourceColumn: votos

		annotation SummarizationSetBy = Automatic

	column diretor
		dataType: string
		lineageTag: 93850d83-f0b8-4ed2-a89c-fdfec8735433
		summarizeBy: none
		sourceColumn: diretor

		annotation SummarizationSetBy = Automatic

	column escritor
		dataType: string
		lineageTag: 0282b726-9517-4e3d-96c1-b6cd96e9cb66
		summarizeBy: none
		sourceColumn: escritor

		annotation SummarizationSetBy = Automatic

	column star
		dataType: string
		lineageTag: 1263df64-eeb0-4113-a188-4745cfe19803
		summarizeBy: none
		sourceColumn: star

		annotation SummarizationSetBy = Automatic

	column genre
		dataType: string
		lineageTag: b9a57d6e-db63-43ea-8ee3-c593307187c0
		summarizeBy: none
		sourceColumn: genre

		annotation SummarizationSetBy = Automatic

	column country_origin
		dataType: string
		lineageTag: 7918b9d6-7026-430a-beb4-a1e172ff34f1
		summarizeBy: none
		sourceColumn: country_origin

		annotation SummarizationSetBy = Automatic

	column production_company
		dataType: string
		lineageTag: a416ed7d-198a-4f1c-8c40-b60d69723334
		summarizeBy: none
		sourceColumn: production_company

		annotation SummarizationSetBy = Automatic

	column language
		dataType: string
		lineageTag: aa2d7945-1c6e-4b02-a422-f7bdecc6a2af
		summarizeBy: none
		sourceColumn: language

		annotation SummarizationSetBy = Automatic

	column win
		dataType: int64
		formatString: 0
		lineageTag: 92c7a4f6-bc66-4d69-8061-dedab8188e25
		summarizeBy: sum
		sourceColumn: win

		annotation SummarizationSetBy = Automatic

	column nomination
		dataType: int64
		formatString: 0
		lineageTag: 75b43c89-c7fe-49ee-b9c7-4c4057cccc68
		summarizeBy: sum
		sourceColumn: nomination

		annotation SummarizationSetBy = Automatic

	column oscar
		dataType: int64
		formatString: 0
		lineageTag: 2f0f1534-5fdc-4862-a7ce-79a410b114b8
		summarizeBy: sum
		sourceColumn: oscar

		annotation SummarizationSetBy = Automatic

	column duracaototal_min
		dataType: string
		lineageTag: 21b55543-11cd-40eb-85f9-7ba024128b22
		summarizeBy: none
		sourceColumn: duracaototal_min

		annotation SummarizationSetBy = Automatic

	column rating_mpa
		dataType: string
		lineageTag: ea12884e-e875-4c0f-89f4-ee42c469d5ea
		summarizeBy: none
		sourceColumn: rating_mpa

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: fa06f2f7-64a8-458d-91bd-31d1ae5014ee
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column gross_world_wide
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: f6717303-1b23-4708-8829-735ff1c6a627
		summarizeBy: sum
		sourceColumn: gross_world_wide

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column gross_us_canada
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 7c302df9-3266-47f8-b534-ebae35464774
		summarizeBy: sum
		sourceColumn: gross_us_canada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column gross_opening_weekend
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 7750f777-4559-447d-b820-0aa5538c290f
		summarizeBy: sum
		sourceColumn: gross_opening_weekend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column filming_location
		dataType: string
		lineageTag: 190cd89a-ea28-4c29-b8c8-91cd0502f9b6
		summarizeBy: none
		sourceColumn: filming_location

		annotation SummarizationSetBy = Automatic

	column Personalizar
		dataType: string
		lineageTag: fe00aae1-44fd-4ce6-9986-b6227ec54743
		summarizeBy: none
		sourceColumn: Personalizar

		annotation SummarizationSetBy = Automatic

	column 'Local de Filmagem Tratado' =
			
			COALESCE('imdb_movies'[filming_location], "Desconhecido")
		lineageTag: e06637aa-afd0-433b-80aa-1f3a93a21eda
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Status de Crítica' = ```
			
			IF(
			    'imdb_movies'[nota] >= 80, 
			    "Excelente", 
			    "Comum"
			)
			```
		lineageTag: 850bb50e-e428-471f-b879-51352c205c88
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition imdb_movies = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\macha\Downloads\Analise_Filmes_BI-master\Analise_Filmes_BI-master\filmes_nova - world_imdb_movies_top_movies_per_year.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"", type text}, {"_1", type text}, {"_2", type text}, {"_3", type text}, {"_4", type text}, {"_5", type text}, {"_6", type text}, {"_7", type text}, {"_8", type text}, {"_9", type text}, {"_10", type text}, {"_11", type text}, {"_12", type text}, {"_13", type text}, {"_14", type text}, {"_15", type text}, {"_16", type text}, {"_17", type text}, {"_18", type text}, {"_19", type text}, {"_20", type text}, {"_21", type text}, {"_22", type text}, {"_23", type text}}),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Tipo Alterado1", [PromoteAllScalars=true]),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos1",{{"", type text}, {"_1", type text}, {"_2", type text}, {"_3", type text}, {"_4", type text}, {"_5", type text}, {"_6", type text}, {"_7", type text}, {"_8", type text}, {"_9", type text}, {"_10", type text}, {"_11", type text}, {"_12", type text}, {"_13", type text}, {"_14", type text}, {"_15", type text}, {"_16", type text}, {"_17", type text}, {"_18", type text}, {"_19", type text}, {"_20", type text}, {"_21", type text}, {"_22", type text}, {"_23", type text}}),
				    #"Cabeçalhos Promovidos2" = Table.PromoteHeaders(#"Tipo Alterado2", [PromoteAllScalars=true]),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos2",{{"id", type text}, {"title", type text}, {"link", type text}, {"year", Int64.Type}, {"duration", type text}, {"rating_mpa", type text}, {"rating_imdb", Int64.Type}, {"vote", Int64.Type}, {"budget", Int64.Type}, {"gross_world_wide", Int64.Type}, {"gross_us_canada", Currency.Type}, {"gross_opening_weekend", Int64.Type}, {"director", type text}, {"writer", type text}, {"star", type text}, {"genre", type text}, {"country_origin", type text}, {"filming_location", type text}, {"production_company", type text}, {"language", type text}, {"captions", type text}, {"win", Int64.Type}, {"nomination", Int64.Type}, {"oscar", Int64.Type}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado3",{"captions"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas1",{{"title", "titulo"}, {"year", "ano"}, {"duration", "duracao"}, {"rating_imdb", "nota"}, {"vote", "votos"}, {"director", "diretor"}, {"writer", "escritor"}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Colunas Renomeadas", {"id"}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Duplicatas Removidas",{{"budget", Currency.Type}, {"gross_world_wide", Currency.Type}, {"gross_opening_weekend", Currency.Type}}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Tipo Alterado4",{{"titulo", Text.Upper, type text}}),
				    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Texto em Maiúscula", {{"genre", each Text.BeforeDelimiter(_, ","), type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Texto Extraído Antes do Delimitador",{"link"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each [nota] <> null and [nota] <> ""),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Linhas Filtradas", "duracao", "duracao - Copiar"),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Duplicada",{{"duracao - Copiar", "duracao em min"}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Renomeadas1",{"id", "titulo", "ano", "duracao", "duracao em min", "rating_mpa", "nota", "votos", "budget", "gross_world_wide", "gross_us_canada", "gross_opening_weekend", "diretor", "escritor", "star", "genre", "country_origin", "filming_location", "production_company", "language", "win", "nomination", "oscar"}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Colunas Reordenadas",{{"duracao em min", "duracao_min"}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Renomeadas2","h","",Replacer.ReplaceText,{"duracao_min"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","m","",Replacer.ReplaceText,{"duracao_min"}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Valor Substituído1", "duracao_min", Splitter.SplitTextByDelimiter(" ", QuoteStyle.None), {"duracao_min.1", "duracao_min.2"}),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"duracao_min.1", Int64.Type}, {"duracao_min.2", Int64.Type}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado5", "duracaototal_min", each ([duracao_min.1]*60) + [duracao_min.2]),
				    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Personalização Adicionada",{"id", "titulo", "ano", "duracao", "duracaototal_min", "duracao_min.1", "duracao_min.2", "rating_mpa", "nota", "votos", "budget", "gross_world_wide", "gross_us_canada", "gross_opening_weekend", "diretor", "escritor", "star", "genre", "country_origin", "filming_location", "production_company", "language", "win", "nomination", "oscar"}),
				    #"Colunas Renomeadas3" = Table.RenameColumns(#"Colunas Reordenadas1",{{"duracao_min.1", "duracaohoras"}}),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Colunas Renomeadas3",{"duracaohoras", "duracao_min.2"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Colunas Removidas2","",null,Replacer.ReplaceValue,{"filming_location"}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Valor Substituído2", "Personalizar", each if [duracaototal_min] <= 65 then "curta_met" else "longa_met"),
				    #"Erros Removidos" = Table.RemoveRowsWithErrors(#"Coluna Condicional Adicionada", {"Personalizar"}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Erros Removidos", each true)
				in
				    #"Linhas Filtradas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

